# 0. 목차

>[1. 행렬의 개념 이해](#scrollTo=BExD16Qj_cM_)

>>[1.1 행렬이란?](#scrollTo=t256VGWcPPZm)

>>[1.2 행렬 만들기](#scrollTo=cqQ_0r23BMGs)

>>>[1.2.1 행렬의 원소를 직접 입력하는 방법](#scrollTo=2PKm13miDB7t)

>>>[1.2.2 일정한 값으로 채워진 행렬 만들기](#scrollTo=rCL-Sg7EE6tj)

>>>[1.2.3 간격이 일정한 행렬: arange, linspace](#scrollTo=_7axcXyB01Up)

>>>[1.2.4 이미 만들어진 행렬을 이용하는 방법](#scrollTo=aVBomke7IdjW)

>[2. 행렬 다루기](#scrollTo=_wbMIOhIL1FL)

>>[2.1 행렬의 인덱싱과 슬라이싱](#scrollTo=NGUx1lAtrNjO)

>>[2.2 행렬의 재형상reshaping](#scrollTo=6A1V1Gj1rROg)

>>[2.3 행렬의 연산](#scrollTo=30-7A194cvqS)

>[3. 행렬을 다루는 numpy 함수](#scrollTo=G24nVuwpNz2o)

>>[3.1 벡터화 연산](#scrollTo=QMKMKkvmOIZU)

>>[3.2 난수 관련 함수](#scrollTo=nKoGizGMOLzJ)



---

# 1. 행렬의 개념 이해

---

## 1.1 행렬이란?

* 행렬: 수를 **사각형** 형태로 나열한 변수
  * 여러 객체를 묶어서 한번에 관리할 수 있다.
  * 대용량 데이터 관리에 편리
  * 인덱스를 통해 각각의 요소에 접근 가능

* 반드시 사각형의 **모든** 칸에 숫자가 차 있어야 한다.
  * 모든 행<sup>row</sup>은 길이가 같아야 한다.
  * 모든 열<sup>column</sup>도 길이가 같아야 한다.
  * (참고) 리스트는 이 조건을 만족하지 않아도 된다.
    * `lst = [[1, 2], [3, 4, 5]]`

<img src=https://www.index.go.kr/potal/e-nara/images/meanAnalsImg/1007/20230414064048076.png width=450>

출처: https://www.index.go.kr/unity/potal/main/EachDtlPageDetail.do?idx_cd=1007

<img src=https://cdn.pixabay.com/photo/2017/07/02/09/03/books-2463779_1280.jpg width=450>

출처: https://pixabay.com/photos/books-bookshelf-library-education-2463779/

* **[중요] 행렬의 인덱스는 0부터 시작한다.**
  * 행 번호를 먼저 쓴다.

![](https://iq.opengenus.org/content/images/2020/04/index.png)

출처: https://iq.opengenus.org/2d-array-in-numpy/

* 행렬과 리스트의 차이점
  * 리스트
    * 아무 자료형이나 다 넣을 수 있다.
    * 요소들이 메모리 상에 인접해있지 않다.
    * 연산이 느리고 용량을 많이 차지한다.
  * 행렬
    * 원소들의 자료형이 동일해야 한다.
    * 원소들이 메모리 상에 인접하게 위치해있다.
    * 연산이 리스트에 비해 빠르다.




In [1]:
import numpy as np

A = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]]) # 모든 행의 길이가 같아야 하고 모든 열의 길이도 같아야 한다.

print(A)

# 14를 꺼내고 싶으면 뭐라고 써야 할까?

# 인덱싱 방법이 리스트와는 약간 다르다! (뒤에서 자세히 설명할 예정)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


---

## 1.2 행렬 만들기

---

### 1.2.1 행렬의 원소를 직접 입력하는 방법

* `numpy.array()`를 이용하여 리스트나 튜플을 행렬로 만들 수 있다.
* numpy의 행렬의 자료형은 ndarray이다.
* 2차원 배열일 경우 각 행의 길이는 같아야 한다.
* 행렬의 shape에 주의할 것
  * shape이 (3,)인 행렬, (1, 3)인 행렬, (3, 1)인 행렬은 모두 다르다!

In [2]:
import numpy as np

# np.array로 리스트를 ndarray로 만든다.
A = np.array([0, 1, 2])
print(A)
print(f'A의 자료형: {type(A)}')
print(f'A의 shape: {A.shape}') # shape은 튜플로 나온다.
print(f'A의 차원: {A.ndim}') # 1차원이다!
print(f'A의 요소의 자료형: {A.dtype}')

[0 1 2]
A의 자료형: <class 'numpy.ndarray'>
A의 shape: (3,)
A의 차원: 1
A의 요소의 자료형: int64


In [3]:
B = np.array([[0.], [1.], [2.]])
print(B)
print(f'B의 shape: {B.shape}') # 2차원 행렬이다!
print(f'B의 차원: {B.ndim}')
print(f'B의 요소의 자료형: {B.dtype}') # 0이 아니라 0.으로 썼으므로 float

[[0.]
 [1.]
 [2.]]
B의 shape: (3, 1)
B의 차원: 2
B의 요소의 자료형: float64


In [4]:
C = np.array([[0, 1, 2]])
print(C)
print(f'C의 shape: {C.shape}')
print(f'C의 차원: {C.ndim}') # 2차원이다! (3,)과는 다른 행렬이다!
print(f'C의 요소의 자료형: {C.dtype}')

[[0 1 2]]
C의 shape: (1, 3)
C의 차원: 2
C의 요소의 자료형: int64


In [5]:
# range도 np.array를 이용하여 ndarray로 만들 수 있다.
# array-like는 다 된다.
D = np.array(range(10))
print(D)

[0 1 2 3 4 5 6 7 8 9]


* ndarray의 복사본을 만들 때는 주의해야 한다.
  * `=`: 복제
  * `numpy.asarray`: 복제
  * `numpy.array`: 복사
  * 입력인자가 ndarray일 경우 =와 asarray는 조심해서 사용해야 한다!
  * 참고: https://ok-lab.tistory.com/179

In [6]:
A = np.array([0, 1, 2, 3, 4])
B = A
C = np.asarray(A)
D = np.array(A)

A[0] = 100

print("B (=):      ", B)
print("C (asarray):", C)
print("D (array):  ", D)

print("B is A?: ", B is A)
print("C is A?: ", C is A)
print("D is A?: ", D is A)

B (=):       [100   1   2   3   4]
C (asarray): [100   1   2   3   4]
D (array):   [0 1 2 3 4]
B is A?:  True
C is A?:  True
D is A?:  False


In [7]:
# ndarray를 만들 때 자료형을 직접 지정할 수도 있다.
A = np.array([0, 1, 2, 3, 4], dtype=float)
print(A)
print(f'A의 요소의 자료형: {A.dtype}')

[0. 1. 2. 3. 4.]
A의 요소의 자료형: float64


In [8]:
# ndarray의 자료형은 변경할 수 없다.
# 자료형을 바꾸려면 새로운 ndarray를 만들어야 한다.
B = A.astype('int') # B는 A의 복사본 (연결되어 있지 않음)
B[0] = 100

print(A, A.dtype) # B를 바꿔도 A는 그대로이다.
print(B, B.dtype)

[0. 1. 2. 3. 4.] float64
[100   1   2   3   4] int64


### 1.2.2 일정한 값으로 채워진 행렬 만들기

* 모든 원소가 같은 행렬을 만들 수 있다.
* 모든 원소가 0인 행렬: `np.zeros`
* 모든 원소가 1인 행렬: `np.ones`
* 모든 원소가 2인 행렬: `2 * np.ones`
* 위 함수들의 입력인자로 행렬 shape을 튜플로 넣는다.
* 자료형 기본값은 `float`이다.

In [9]:
print(np.zeros((2, 3))) # np.zeros(2, 3)으로 쓰지 않도록 조심하자.

print(np.ones((3, 4)))

print(10 * np.ones((3, 4)))

print(np.ones(5))

print(np.zeros(5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


### 1.2.3 간격이 일정한 행렬: arange, linspace

* 일정한 간격으로 값을 생성하고 싶을 때 사용
* 간격을 지정하고 싶으면: `arange`
* 개수를 지정하고 싶으면: `linspace`


* `np.arange`: 간격을 지정하고 싶을 때
  * 문법: `numpy.arange([start, ]stop, [step, ])`
  * start의 기본값은 0, step의 기본값은 1
  * 입력 인자가 1개이면 stop이 됨
  * 입력 인자가 2개이면 start와 stop이 됨
  * `np.arange(0, 10, 1)`: 0부터 10까지 1 간격으로 (10은 포함되지 **않음!** - half-open interval)
  * `np.arange(10, 0, -2)`: 음수 간격도 가능
  * `np.arange(0, 1, 0.1)`: 소수 간격도 가능 (`range`와의 차이점)

In [10]:
# 문법: numpy.arange([start, ]stop, [step, ])
print(np.arange(0., 10, 1)) # 0과 0.의 차이는?
print(np.arange(10, 0, -2)) # arange는 입력값으로부터 자료형을 추론함
print("="*40)
print(np.arange(10)) # range(10)과 같음
print(np.arange(10, 20)) # range(10, 20)과 같음
print(np.arange(10, 20, 2)) # range(10, 20, 2)와 같음
print(np.arange(20, 10, -2)) # range(20, 10, -2)와 같음
print("="*40)
print(np.arange(10, 5)) # 10에서 1씩 증가하여 5가 될 수 없으므로 빈 행렬
print(np.arange(1, 100, 10)) # 끝에 도달할 수 없으면 도달 가능한 마지막 값까지
print("="*40)
print(np.arange(1.5, 2.5, 0.1)) # 소수 간격 가능

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[10  8  6  4  2]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[20 18 16 14 12]
[]
[ 1 11 21 31 41 51 61 71 81 91]
[1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4]


* `np.linspace`: 전체 값 개수를 지정하고 싶을 때
  * 문법: `linspace(start, stop, num=50)`
  * start에서 stop까지 등간격으로 num개만큼 생성
  * num을 지정하지 않으면 기본으로 50개 생성
  * `np.linspace(0, 10, 11)`: 0부터 10까지 등간격으로 11개 (10이 **포함됨!**)
  * `np.linspace(5, -5, 11)`: 개수를 지정하므로 간격의 부호를 신경쓰지 않아도 됨

In [11]:
# 문법: numpy.linspace(start, stop, num=50)
print(np.linspace(1, 10, 10)) # linspace는 결과가 정수이더라도 float으로 만든다.
print(np.linspace(1, 9, 5))
print(np.linspace(2, 100)) # 개수 지정하지 않으면 50개
print(np.linspace(9, 1, 5)) # 개수를 지정하므로 간격의 부호는 신경쓰지 않아도 된다.
print(np.linspace(10, 10)) # 시작과 끝값이 같다면? 같은 값이 반복됨

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 3. 5. 7. 9.]
[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.
  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.
  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.
  86.  88.  90.  92.  94.  96.  98. 100.]
[9. 7. 5. 3. 1.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


* 언제 arange를 쓰고 언제 linspace를 쓸까?
  * 간격을 지정하는 것이 더 편할 때는 `np.arange`
    * ex) 20초부터 10초 간격으로 100초까지
      * t = np.arange(20, 101, 10)
    * ex) 1990년부터 2020년까지 5년 간격으로
      * years = np.arange(1990, 2021, 5)
  * 간격이 중요하지 않을 때에는 `np.linspace`
    * 특히 시작과 끝값만 정하고 촘촘히 나눌 때
    * ex) 0부터 1까지 충분히 많은 - 1000개 정도 - 값을 등간격으로
      * t = np.linspace(0, 1, 1000)

---

### 1.2.4 이미 만들어진 행렬을 이용하는 방법
* 같이 읽기
  * https://everyday-image-processing.tistory.com/86
  * https://everyday-image-processing.tistory.com/87
  
* 이미 만들어진 행렬을 다양한 방법으로 합칠 수 있다.
* (1, 3) 행렬과 (1, 3) 행렬을
  * 수평 방향으로 합치면 (1, 6) 행렬이 만들어진다.
  * 수직 방향으로 합치면 (2, 3) 행렬이 만들어진다.

* ndarray에는 axis라는 개념이 있다.
  * 1차원 행렬은 축이 하나밖에 없으므로 `axis=0`만 있다.
  * 2차원 행렬은
    * `axis=0`은 행방향(수직 방향)을 말한다. (또는 첫 번째 차원)
    * `axis=1`은 열방향(수평 방향)을 말한다. (또는 두 번째 차원)

<p>
<img src=https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcSoMOs%2Fbtqt0a2Dc2y%2FQhkfwhiWqeUKvNfsM2H29K%2Fimg.png width=450>
</p>

출처: https://azanewta.tistory.com/3

* 행렬을 합치는 함수는 종류가 다양하다.
* `concatenate((a1, a2, ...), axis)`
  * 각 행렬은 차원이 같아야 한다.
  * 각 행렬은 합칠 수 있는 크기를 가져야 한다.
  * (2, 2)와 (1, 2) -> `axis=0` 방향으로 합칠 수 있지만 `axis=1` 방향으로는 못 합친다.

<p>
<img src=https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fbctbkn%2FbtqHelWh9tf%2FHuwyP0ckFAkWpdAxqm0wk1%2Fimg.png width=450></p>

출처: https://everyday-image-processing.tistory.com/86

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1차원은 axis=0로만 합칠 수 있다.
print(np.concatenate((a, b), axis=0))

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]]) # 1차원 행렬로 만들면 a와 concatenate로 합칠 수 없다.
print(np.concatenate((a, b), axis=0)) # axis=1로는 합칠 수 없다.

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


* `stack((a1, a2, ...), axis)`
  * 1차원 ndarray를 합쳐서 2차원로 만들 때 사용할 수 있다.
  * 합칠 축을 지정하면 다른 방향으로도 합칠 수 있다.
<p>
<img src=https://www.w3resource.com/w3r_images/numpy-manipulation-stack-function-image-1.png width=200>
</p>

출처: https://www.w3resource.com/numpy/manipulation/stack.php

* `hstack((a1, a2, ...))`
  * 수평<sup>**h**orizontal</sup> 방향으로 합친다.
  * 합칠 행렬들은 차원이 같아야 한다.
  * `concatenate`에서 `axis=1`로 둔 것과 같은 효과이다.

* `vstack((a1, a2, ...))`
  * 수직<sup>**v**ertical</sup> 방향으로 합친다.
  * 합칠 행렬들은 차원이 같아야 한다.
  * `concatenate`에서 `axis=0`으로 둔 것과 같은 효과이다.

<p>
<img src=https://i.stack.imgur.com/hSM5G.png width=600>
</p>

출처: https://i.stack.imgur.com/hSM5G.png

In [13]:
h1 = np.array([1, 2, 3]) # shape = (3,)
h2 = np.array([4, 5, 6]) # shape = (3,)
v1 = np.array([[1], [2], [3]]) # shape = (3, 1)
v2 = np.array([[4], [5], [6]]) # shape = (3, 1)

print(np.hstack((h1, h2))) # shape = (6,)
print(np.vstack((h1, h2))) # shape = (2, 3)

print(np.hstack((v1, v2))) # shape = (3, 2)
print(np.vstack((v1, v2))) # shape = (6, 1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [14]:
# arange, linspace와 함께 사용하기

print(np.hstack((np.arange(1, 4), np.arange(4, 8))))
print(np.vstack((np.arange(1, 6), np.arange(6, 11))))
print(np.vstack((np.linspace(10, 20, 6), np.linspace(20, 30, 6))))

[1 2 3 4 5 6 7]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10. 12. 14. 16. 18. 20.]
 [20. 22. 24. 26. 28. 30.]]


* `tile(A, reps)`
  * ndarray `A`를 `reps`만큼 반복해서 더 큰 행렬을 만든다.


<p>
<img src=https://www.w3resource.com/w3r_images/numpy-manipulation-tile-function-image-a.png>
</p>

출처: https://www.w3resource.com/numpy/manipulation/tile.php

In [15]:
a = np.array([0, 1, 2])
print(np.tile(a, 2)) # 가로 방향으로 2번 반복
print(np.tile(a, (2, 3))) # 행방향으로 2번, 열방향으로 3번 반복
print(np.tile(a, (4, 1))) # 행방향으로 4번, 열방향으로 1번 반복
print('='*40)
b = np.array([[1, 2], [3, 4]])
print(np.tile(b, 2))
print(np.tile(b, (2, 2)))

[0 1 2 0 1 2]
[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[1 2 1 2]
 [3 4 3 4]]
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


---

# 2. 행렬 다루기

* 행렬의 인덱싱과 슬라이싱은 기본적으로 리스트, 튜플과 유사하다.
* 행렬의 재형상을 통해 다양한 모양으로 바꿀 수 있다.
* 행렬을 연산하는 방법도 다룬다.

---

## 2.1 행렬의 인덱싱과 슬라이싱

* 시퀀스 자료형과 같은 점
  * 인덱싱: [n] = n 번째
  * 슬라이싱: [m:n] = m 번째부터 n 번째까지
  * 끝 요소는 포함하지 않는다. (half-open interval)
  * 음수는 뒤에서부터, -1은 맨 뒤
  * 콜론 앞을 생략하면 처음부터
  * 콜론 뒤를 생략하면 맨 뒤까지
  * 인덱싱의 결과는 요소, 슬라이싱의 결과는 ndarray
  * 콜론 앞뒤로 숫자가 없으면 행 또는 열 전체를 뜻한다.

* 시퀀스 자료형과 다른 점
  * 2차원 이상의 행렬인 경우 아래의 포맷을 이용한다.
    * [행범위, 열범위]
    * 예: [1:4, 2:5]

* 주의할 점
  * 슬라이싱의 결과는 원래의 행렬과 요소를 공유한다. (리스트가 참조형임을 떠올릴 것)
  * 복사를 해야 할 경우 `copy()`를 해야 한다.

In [16]:
# 1차원 행렬의 인덱싱과 슬라이싱
a = np.arange(0, 11) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# 인덱싱
print(a[0], a[-1], a[4])

# 슬라이싱
print(a[1:5]) # 5는 포함하지 않음
print(a[1:-1]) # 1번째부터 마지막 직전까지 (-1은 포함하지 않으므로)
print(a[1:-1:2]) # 1부터 -1번째까지 2칸씩 뛰면서
print(a[:5]) # 처음부터 5번째 전까지, 즉 처음 5개의 원소
print(a[-5:]) # -5번째부터 끝까지, 즉 마지막 5개의 원소

# 순서 뒤집기
print(a[::-1]) # ::는 전체를 뜻하며, -1은 순서를 뒤집음을 뜻함

0 10 4
[1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0 1 2 3 4]
[ 6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


* 2차원 행렬의 슬라이싱


<p>
<img src=https://miro.medium.com/v2/resize:fit:1400/1*W9DYV8pLr8AKVXJefwJBng.png width=600>
</p>

출처: https://towardsdatascience.com/slicing-numpy-arrays-like-a-ninja-e4910670ceb0

In [17]:
# 2차원 행렬의 인덱싱과 슬라이싱

A = [[10*i + j for j in range(6)] for i in range(6)] # 리스트 컴프리헨션: 나중에 배우게 됨
A = np.array(A)
print(A)
print('='*40)
print(A[3, 4]) # 숫자를 바꿔가며 테스트해보자.
print('='*40)
print(A[1:3, 1:4]) # 숫자를 바꿔가며 테스트해보자.
print('='*40)
print(A[2, :]) # 2번째 행 전체
print(A[:, 1]) # 1번째 열 전체, 1 대신 1:2를 쓰면?

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
34
[[11 12 13]
 [21 22 23]]
[20 21 22 23 24 25]
[ 1 11 21 31 41 51]


In [18]:
print(A[:3, :3])
print(A[3:, :3])

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
[[30 31 32]
 [40 41 42]
 [50 51 52]]


* 슬라이싱의 반환 행렬은
  * 원래 행렬과 같은 요소를 참조한다.
  * 슬라이싱 한 것의 요소를 바꾸면 원래 행렬도 바뀐다.
* 이를 방지하기 위해 `copy()` 메서드를 사용해야 한다.

In [19]:
print(A)
B = A[:3, :3]
B[:, :] = 0
print(A)

C = A[3:, 3:].copy()
C[:, :] = 1
print(C)
print(A)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[ 0  0  0  3  4  5]
 [ 0  0  0 13 14 15]
 [ 0  0  0 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 0  0  0  3  4  5]
 [ 0  0  0 13 14 15]
 [ 0  0  0 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


* 인덱스는 임의의 정수 배열일 수 있다.
  * 반드시 콜론을 사용해야 하는 것이 아니다.

In [20]:
A = np.linspace(0, 1, 11) # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
print(A[[0, 1, 2]]) # 숫자를 바꿔가며 테스트해보자.

[0.  0.1 0.2]


* 부울<sup>bool</sup> 배열을 이용하는 방법도 있다.
* 조건문에서 한 번 더 다룰 예정이다.

In [21]:
B = A > 0.5
print(B)
print(A[A > 0.5])

[False False False False False False  True  True  True  True  True]
[0.6 0.7 0.8 0.9 1. ]


* 행렬 수정하기
  * 특정 위치의 값 바꾸기
  * 특정 범위의 값 바꾸기

In [22]:
A = [[10*i + j for j in range(5)] for i in range(4)] # 나중에 배우게 됨
A = np.array(A)
print(A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [23]:
# [1, 2] 위치의 값을 100으로 바꾸기
A[1, 2] = 100
print(A)

# 2번째 열을 [100, 101, 102, 103]으로 바꾸기
A[:, 2] = np.arange(100, 104) # 길이가 같으면 자동으로 맞춰서 넣어준다.
print(A)

[[  0   1   2   3   4]
 [ 10  11 100  13  14]
 [ 20  21  22  23  24]
 [ 30  31  32  33  34]]
[[  0   1 100   3   4]
 [ 10  11 101  13  14]
 [ 20  21 102  23  24]
 [ 30  31 103  33  34]]


In [24]:
# 2~3번째 열 전체를 -1로 바꾸기
A[:, 2:4] = -1
print(A)

# 2~끝 행 전체를 42로 바꾸기
A[2:, :] = 42
print(A)

[[ 0  1 -1 -1  4]
 [10 11 -1 -1 14]
 [20 21 -1 -1 24]
 [30 31 -1 -1 34]]
[[ 0  1 -1 -1  4]
 [10 11 -1 -1 14]
 [42 42 42 42 42]
 [42 42 42 42 42]]


In [25]:
# 2~3번 행, 0~1번 열 영역을 [[77, 78], [79, 80]]으로 바꾸기
A[2:4, 0:2] = np.array([[77, 78], [79, 80]])
print(A)

[[ 0  1 -1 -1  4]
 [10 11 -1 -1 14]
 [77 78 42 42 42]
 [79 80 42 42 42]]


---

## 2.2 행렬의 재형상<sup>reshaping</sup>

* 행렬의 원소를 재배치하는 방법을 다룬다.
  * `reshape`: 예를 들어 3x4 행렬을 2x6으로 변경
  * `flatten`: 2차원 행렬을 1차원으로 변경
  * `T`: 전치행렬
  * `append`: 행렬의 끝부분에 값을 덧붙임 (리스트의 append와 유사)
  * `fliplr`: 좌우를 뒤집음 (lr = left right)
  * `flipud`: 위아래를 뒤집음 (ud = up down)

In [26]:
# reshape: 행렬의 원소 개수를 유지하며 크기만 바꿈
# np.reshape, ndarray.reshape 모두 가능
# 원 행렬을 바꾸지 않고 새로운 행렬을 반환하나, 새 행렬은 원 행렬과 같은 객체를 가리킴

a = np.arange(6) # [0 1 2 3 4 5]
print(a.reshape((3, 2))) # a는 바꾸지 않고 새로운 행렬을 반환한다.
print(np.reshape(a, (2, 3)))
print(a)

b = a.reshape((3, 2))
print(b.reshape(6)) # 1차원 행렬
print(b.reshape((1, 6))) # 2차원 행렬

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 1 2 3 4 5]]


In [27]:
b[0, 0] = 100
print(a) # b는 a와 객체를 공유함
c = b.copy()
c[0, 0] = 200
print(c)
print(a)

[100   1   2   3   4   5]
[[200   1]
 [  2   3]
 [  4   5]]
[100   1   2   3   4   5]


In [28]:
# flatten: 행렬을 1차원으로 flat하게 만든다.
# 원 행렬과 다른 객체를 가리키는 복사본을 만든다.

a = np.arange(6).reshape((3, 2)) # [[0 1] [2 3] [4 5]]
print(a)
b = a.flatten()
print(b)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]
(6,)


* 전치행렬<sup>transpose</sup>을 만드는 방법
  * 행렬 `a`를 전치시키려면 `a.T`를 쓰면 되는데...
  * 2차원 행렬에는 잘 동작하는데...
  * 1차원 행렬(행벡터)은 차원이 1개밖에 없으므로 전치가 되지 않는다.
  * 방법: 2차원으로 만든다.


In [29]:
# 전치행렬: ndarray.T
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.T)

b = np.array([0, 1, 2, 3])
print(b.T) # 전치가 되지 않는다.

b = np.array([b]) # 차원을 늘린다.
print(b.shape)
print(b.T)

[[1 3 5]
 [2 4 6]]
[0 1 2 3]
(1, 4)
[[0]
 [1]
 [2]
 [3]]


In [30]:
# np.append: 행렬 끝에 값을 덧붙임 (리스트의 append를 생각하면 됨)

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

print(np.append(a, b)) # 축을 지정하지 않으면 flatten을 한다.
print(np.append(a, b, axis=0)) # 에러 발생 -> 어떻게 수정해야 할까?

[1 2 3 4 5 6 7 8 9]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
# np.fliplr: 좌우를 뒤집음 (lr = left right)
# np.flipud: 좌우를 뒤집음 (ud = up down)
A = np.arange(9).reshape((3, 3))
print(A)
print(np.fliplr(A))
print(np.flipud(A))

---

## 2.3 행렬의 연산

* 두 행렬의 사칙연산
  * 크기가 같으면: 원소끼리 연산한다.
  * 크기가 다르면: 브로드캐스팅
* 행렬과 스칼라의 사칙연산
  * 원소별로 연산한다.

In [ ]:
# 행렬 + 행렬
a = np.arange(0, 5) # [0, 1, 2, 3, 4]
b = np.arange(10, 15) # [10, 11, 12, 13, 14]
print(a + b)
print(a - b)

# 행렬 + 스칼라, 스칼라 + 행렬
c = a + 10
print(c)
print(c + 10)
print(20 - c)

In [ ]:
# 행렬과 스칼라의 곱셈과 나눗셈
p = np.arange(4, 24, 4) # [4 8 12 16 20]
q = p * 2
print(q)
print(2 * q)
print(q / 8) # 나눗셈은 float
print(8 / q)

In [ ]:
# 행렬의 원소별 곱셈
a = np.array([1, 2, 3])
b = np.array([4, 3, 1])
print(a * b)

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[3, 3, 4], [3, 1, 2]])
print(A * B)

print(A ** 2)

In [ ]:
# 행렬의 원소별 나눗셈
a = np.array([1, 2, 3])
b = np.array([4, 3, 1])
print(a / b)

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[3, 3, 4], [3, 1, 2]])
# A / B = [[1/3, 2/3, 3/4],
#          [4/3, 5/1, 6/2]]
print(A / B)

* 브로드캐스팅<sup>broadcasting</sup>이란?
  * 크기가 다른 행렬끼리 연산하려는 경우
  * 피연산자의 크기가 같은 차원이 있다면
  * 크기가 다른 차원을 알아서 맞춰준다.
  * 예1) (3, 3)과 (1, 3)을 연산하는 경우
    * (1, 3)을 행방향으로 복제해서 (3, 3)으로 만들고 연산한다.
  * 예2) (3, 1)과 (3, 3)을 연산하는 경우
    * (3, 1)을 열방향으로 복제해서 (3, 3)으로 만들고 연산한다.

<p>
<img src=https://miro.medium.com/v2/resize:fit:1400/1*lY8Ve6Uz_bqVI5NPh5RPZA.png width=600>
</p>

출처: https://towardsdatascience.com/broadcasting-in-numpy-58856f926d73

In [ ]:
A = np.arange(12).reshape((3, 4))
print(A)
print(A + 10 * np.ones(4))
print(A * np.array([[1], [2], [3]]))

---

# 3. 행렬을 다루는 numpy 함수

---

## 3.1 벡터화 연산

* 1주차에 다뤘던 많은 함수들
  * `np.sqrt`, `np.log`, `np.sin`, ...
* 이 함수들은 행렬을 입력으로 받아 행렬을 반환한다.
* 당연히 각 원소에 대한 함수값이 원래 위치에 들어간다.

In [ ]:
A = np.arange(1, 11)
print(np.sqrt(A))
print(np.log10(A))

q = np.linspace(0, 2*np.pi, 11)
print(np.sin(q))

* 행렬을 다루는 numpy 함수들
  * `np.sum`: 원소의 합
  * `np.mean`: 원소의 평균
  * `np.std`: 표준편차
  * `np.prod`: 원소의 곱
  * `np.cumsum`: 원소의 누적 합
  * `np.cumprod`: 원소의 누적 곱
  * `np.min`: 원소의 최소값
  * `np.max`: 원소의 최대값
  * `np.argmin`: 원소의 최소값의 인덱스
  * `np.argmax`: 원소의 최대값의 인덱스
  * `np.all`: 모든 원소가 nonzero인지?
  * `np.any`: 하나라도 nonzero인지?


In [ ]:
A = np.arange(0, 12).reshape((3, 4))
print(A)
print('='*40)
print(np.sum(A)) # 모든 원소의 합
print(np.sum(A, axis=0)) # 0번 축방향으로의 합
print(np.sum(A, axis=1)) # 1번 축방향으로의 합
print('='*40)
print(np.mean(A)) # 모든 원소의 평균
print(np.mean(A, axis=0)) # 0번 축방향으로의 평균
print(np.mean(A, axis=1)) # 1번 축방향으로의 평균
print('='*40)
print(np.std(A)) # 모든 원소의 표준편차
print(np.std(A, axis=0)) # 0번 축방향으로의 표준편차
print(np.std(A, axis=1)) # 1번 축방향으로의 표준편차

In [ ]:
A = np.arange(1, 13).reshape((3, 4))
print(A)
print(np.prod(A))
print(np.prod(A, axis=0))
print(np.prod(A, axis=1))

In [ ]:
print(A)
print(A.flatten())
print(np.cumsum(A))
print(np.cumsum(A, axis=0))
print(np.cumsum(A, axis=1))

In [ ]:
print(A)
A[[0, 1], :] = A[[1, 0], :] # 0번째와 1번째 행 swap
print(A)
A[:, [0, 2]] = A[:, [2, 0]] # 0번째와 2번째 열 swap
print(A)

print(np.min(A))
print(np.min(A, axis=0))
print(np.min(A, axis=1))

In [ ]:
print(A)
print(np.argmin(A)) # 1차원 인덱싱일 때 전체 원소 중 최소값의 인덱스
print(np.argmin(A, axis=0)) # 0번 축방향으로 최소값의 인덱스
print(np.argmin(A, axis=1)) # 1번 축방향으로 최소값의 인덱스

In [ ]:
A = np.array([0, 1, 2, 3])
print(np.all(A)) # 전부(all) nonzero인가?
print(np.any(A)) # 하나라도(any) nonzero인가?

---

## 3.2 난수 관련 함수

* 우선 seed를 고정하고 시작한다.
* 원래 난수는 말 그대로 랜덤하게 값을 만드는 것이므로,
* 사람마다 숫자가 다르게 나온다.
* 하지만 seed를 고정하면 모두에게 같은 값이 나오게 할 수 있다.

In [ ]:
np.random.seed(42) # 주석을 풀고 실행해보자.

print(np.random.random(3))
print(np.random.random(3)) # 한번 더 한다고 똑같이 나오지는 않는다.

* `np.random.rand()`: [0, 1) 범위의 균등분포 난수 1개 생성
  * `np.random.rand(d1, d2)`: shape이 `(d1, d2)`인 난수 행렬 생성

In [ ]:
np.random.seed(42)

print(np.random.rand(3, 4))

import matplotlib.pyplot as plt

x = np.random.rand(10000) # shape이 (10000,)인 난수 생성
plt.hist(x, bins=25, edgecolor='k')
plt.show()

* `np.random.randn()`: 평균이 0이고 표준편차가 1인 정규분포의 난수 1개 생성
  * `np.random.randn(d1, d2)`: shape이 `(d1, d2)`인 난수 행렬 생성

In [ ]:
np.random.seed(42)

print(np.random.randn(3, 4))

x = np.random.randn(10000) # shape이 (10000,)인 난수 생성
plt.hist(x, bins=25, edgecolor='k')
plt.show()

* `np.random.randint`: 정수 난수 생성
  * `np.random.randint(high)`: [0, high) 범위의 정수 난수 1개
  * `np.random.randint(low, high)`: [low, high) 범위의 정수 난수 1개
  * `np.random.randint(low, high, size=10)`: [low, high) 범위의 정수 난수를 (10,)의 shape으로 생성
  * `np.random.randint(low, high, size=(2, 4))`: [low, high) 범위의 정수 난수를 (2, 4)의 shape으로 생성
  

In [ ]:
np.random.seed(42)

print(np.random.randint(5, size=20)) # 0, 1, 2, 3, 4 중

print(np.random.randint(5, 10, size=20)) # 5, 6, 7, 8, 9 중